name: Deploy serial-viewer
  
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.NAS_SSH_KEY }}

      - name: Add NAS to known hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -p ${{ secrets.NAS_SSH_PORT }} -H ${{ secrets.NAS_HOST }} >> ~/.ssh/known_hosts

      - name: Generate version.txt
        run: |
          mkdir -p serial-viewer/public
          version=$(git log -1 --date=short --format="%cd")
          echo "$version" > serial-viewer/public/version.txt
          echo "Version générée: $version"

      - name: Rebuild & Restart serial-viewer container
        run: |
          ssh -p ${{ secrets.NAS_SSH_PORT }} ${{ secrets.NAS_USER }}@${{ secrets.NAS_HOST }} "
            set -e
            cd /volume1/docker/serial-viewer &&
            git config --global --add safe.directory /volume1/docker/serial-viewer &&
            git fetch origin &&
            git reset --hard origin/main &&
            git clean -fd &&
            mkdir -p public &&
            echo '$version' > public/version.txt &&
            /usr/local/bin/docker-compose build &&
            /usr/local/bin/docker-compose up -d
          "
